/*
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.salesforce.marketingcloud.javasdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.salesforce.marketingcloud.javasdk.model.AssetType;
import com.github.salesforce.marketingcloud.javasdk.model.SharingProperties;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * Asset
 */

public class Asset {
  @SerializedName(value = "Id", alternate = "id")
  private BigDecimal id = null;

  @SerializedName(value = "CustomerKey", alternate = "customerKey")
  private String customerKey = null;

  @SerializedName("ContentType")
  private String contentType = null;

  @SerializedName("Data")
  private Object data = null;

  @SerializedName("AssetType")
  private AssetType assetType = null;

  @SerializedName("Version")
  private BigDecimal version = null;

  @SerializedName("Locked")
  private Boolean locked = null;

  @SerializedName("FileProperties")
  private Object fileProperties = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("Description")
  private String description = null;

  @SerializedName("Category")
  private Object category = null;

  @SerializedName("Tags")
  private List<String> tags = null;

  @SerializedName("Content")
  private String content = null;

  @SerializedName("Design")
  private String design = null;

  @SerializedName("SuperContent")
  private String superContent = null;

  @SerializedName("CustomFields")
  private Object customFields = null;

  @SerializedName("Views")
  private Object views = null;

  @SerializedName("Blocks")
  private Object blocks = null;

  @SerializedName("MinBlocks")
  private BigDecimal minBlocks = null;

  @SerializedName("MaxBlocks")
  private BigDecimal maxBlocks = null;

  @SerializedName("Channels")
  private Object channels = null;

  @SerializedName("AllowedBlocks")
  private List<String> allowedBlocks = null;

  @SerializedName("Slots")
  private Object slots = null;

  @SerializedName("BusinessUnitAvailability")
  private Object businessUnitAvailability = null;

  @SerializedName("sharingProperties")
  private SharingProperties sharingProperties = null;

  @SerializedName("Template")
  private Object template = null;

  @SerializedName("File")
  private String file = null;

  @SerializedName("GenerateFrom")
  private String generateFrom = null;

  public Asset id(BigDecimal id) {
    this.id = id;
    return this;
  }

   /**
   * The id of the asset
   * @return id
  **/
  @ApiModelProperty(value = "The id of the asset")
  public BigDecimal getId() {
    return id;
  }

  public void setId(BigDecimal id) {
    this.id = id;
  }

  public Asset customerKey(String customerKey) {
    this.customerKey = customerKey;
    return this;
  }

   /**
   * Reference to customer&#39;s private ID/name for the asset
   * @return customerKey
  **/
  @ApiModelProperty(required = true, value = "Reference to customer's private ID/name for the asset")
  public String getCustomerKey() {
    return customerKey;
  }

  public void setCustomerKey(String customerKey) {
    this.customerKey = customerKey;
  }

  public Asset contentType(String contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * The type that the content attribute will be in
   * @return contentType
  **/
  @ApiModelProperty(value = "The type that the content attribute will be in")
  public String getContentType() {
    return contentType;
  }

  public void setContentType(String contentType) {
    this.contentType = contentType;
  }

  public Asset data(Object data) {
    this.data = data;
    return this;
  }

   /**
   * Property bag containing the asset data
   * @return data
  **/
  @ApiModelProperty(value = "Property bag containing the asset data")
  public Object getData() {
    return data;
  }

  public void setData(Object data) {
    this.data = data;
  }

  public Asset assetType(AssetType assetType) {
    this.assetType = assetType;
    return this;
  }

   /**
   * Get assetType
   * @return assetType
  **/
  @ApiModelProperty(required = true, value = "")
  public AssetType getAssetType() {
    return assetType;
  }

  public void setAssetType(AssetType assetType) {
    this.assetType = assetType;
  }

  public Asset version(BigDecimal version) {
    this.version = version;
    return this;
  }

   /**
   * The version of the asset
   * @return version
  **/
  @ApiModelProperty(value = "The version of the asset")
  public BigDecimal getVersion() {
    return version;
  }

  public void setVersion(BigDecimal version) {
    this.version = version;
  }

  public Asset locked(Boolean locked) {
    this.locked = locked;
    return this;
  }

   /**
   * Specifies if the asset can be modified or not
   * @return locked
  **/
  @ApiModelProperty(value = "Specifies if the asset can be modified or not")
  public Boolean isLocked() {
    return locked;
  }

  public void setLocked(Boolean locked) {
    this.locked = locked;
  }

  public Asset fileProperties(Object fileProperties) {
    this.fileProperties = fileProperties;
    return this;
  }

   /**
   * Stores the different properties that this asset refers to if it is a file type
   * @return fileProperties
  **/
  @ApiModelProperty(value = "Stores the different properties that this asset refers to if it is a file type")
  public Object getFileProperties() {
    return fileProperties;
  }

  public void setFileProperties(Object fileProperties) {
    this.fileProperties = fileProperties;
  }

  public Asset name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the asset, set by the client
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name of the asset, set by the client")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Asset description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the asset, set by the client
   * @return description
  **/
  @ApiModelProperty(required = true, value = "Description of the asset, set by the client")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Asset category(Object category) {
    this.category = category;
    return this;
  }

   /**
   * ID of the category the asset belongs to
   * @return category
  **/
  @ApiModelProperty(value = "ID of the category the asset belongs to")
  public Object getCategory() {
    return category;
  }

  public void setCategory(Object category) {
    this.category = category;
  }

  public Asset tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public Asset addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<String>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * List of tags associated with the asset
   * @return tags
  **/
  @ApiModelProperty(value = "List of tags associated with the asset")
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  public Asset content(String content) {
    this.content = content;
    return this;
  }

   /**
   * The actual content of the asset
   * @return content
  **/
  @ApiModelProperty(value = "The actual content of the asset")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public Asset design(String design) {
    this.design = design;
    return this;
  }

   /**
   * Fallback for display when neither content nor supercontent are provided
   * @return design
  **/
  @ApiModelProperty(value = "Fallback for display when neither content nor supercontent are provided")
  public String getDesign() {
    return design;
  }

  public void setDesign(String design) {
    this.design = design;
  }

  public Asset superContent(String superContent) {
    this.superContent = superContent;
    return this;
  }

   /**
   * Content that supersedes content in terms of display
   * @return superContent
  **/
  @ApiModelProperty(value = "Content that supersedes content in terms of display")
  public String getSuperContent() {
    return superContent;
  }

  public void setSuperContent(String superContent) {
    this.superContent = superContent;
  }

  public Asset customFields(Object customFields) {
    this.customFields = customFields;
    return this;
  }

   /**
   * Custom fields within an asset
   * @return customFields
  **/
  @ApiModelProperty(value = "Custom fields within an asset")
  public Object getCustomFields() {
    return customFields;
  }

  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }

  public Asset views(Object views) {
    this.views = views;
    return this;
  }

   /**
   * Views within an asset
   * @return views
  **/
  @ApiModelProperty(value = "Views within an asset")
  public Object getViews() {
    return views;
  }

  public void setViews(Object views) {
    this.views = views;
  }

  public Asset blocks(Object blocks) {
    this.blocks = blocks;
    return this;
  }

   /**
   * Blocks within the asset
   * @return blocks
  **/
  @ApiModelProperty(value = "Blocks within the asset")
  public Object getBlocks() {
    return blocks;
  }

  public void setBlocks(Object blocks) {
    this.blocks = blocks;
  }

  public Asset minBlocks(BigDecimal minBlocks) {
    this.minBlocks = minBlocks;
    return this;
  }

   /**
   * Minimum number of blocks within an asset
   * @return minBlocks
  **/
  @ApiModelProperty(value = "Minimum number of blocks within an asset")
  public BigDecimal getMinBlocks() {
    return minBlocks;
  }

  public void setMinBlocks(BigDecimal minBlocks) {
    this.minBlocks = minBlocks;
  }

  public Asset maxBlocks(BigDecimal maxBlocks) {
    this.maxBlocks = maxBlocks;
    return this;
  }

   /**
   * Maximum number of blocks within an asset
   * @return maxBlocks
  **/
  @ApiModelProperty(value = "Maximum number of blocks within an asset")
  public BigDecimal getMaxBlocks() {
    return maxBlocks;
  }

  public void setMaxBlocks(BigDecimal maxBlocks) {
    this.maxBlocks = maxBlocks;
  }

  public Asset channels(Object channels) {
    this.channels = channels;
    return this;
  }

   /**
   * List of channels that are allowed to use this asset
   * @return channels
  **/
  @ApiModelProperty(value = "List of channels that are allowed to use this asset")
  public Object getChannels() {
    return channels;
  }

  public void setChannels(Object channels) {
    this.channels = channels;
  }

  public Asset allowedBlocks(List<String> allowedBlocks) {
    this.allowedBlocks = allowedBlocks;
    return this;
  }

  public Asset addAllowedBlocksItem(String allowedBlocksItem) {
    if (this.allowedBlocks == null) {
      this.allowedBlocks = new ArrayList<String>();
    }
    this.allowedBlocks.add(allowedBlocksItem);
    return this;
  }

   /**
   * List of blocks that are allowed in the asset
   * @return allowedBlocks
  **/
  @ApiModelProperty(value = "List of blocks that are allowed in the asset")
  public List<String> getAllowedBlocks() {
    return allowedBlocks;
  }

  public void setAllowedBlocks(List<String> allowedBlocks) {
    this.allowedBlocks = allowedBlocks;
  }

  public Asset slots(Object slots) {
    this.slots = slots;
    return this;
  }

   /**
   * Slots within the asset
   * @return slots
  **/
  @ApiModelProperty(value = "Slots within the asset")
  public Object getSlots() {
    return slots;
  }

  public void setSlots(Object slots) {
    this.slots = slots;
  }

  public Asset businessUnitAvailability(Object businessUnitAvailability) {
    this.businessUnitAvailability = businessUnitAvailability;
    return this;
  }

   /**
   * A dictionary of member IDs that have been granted access to the asset
   * @return businessUnitAvailability
  **/
  @ApiModelProperty(value = "A dictionary of member IDs that have been granted access to the asset")
  public Object getBusinessUnitAvailability() {
    return businessUnitAvailability;
  }

  public void setBusinessUnitAvailability(Object businessUnitAvailability) {
    this.businessUnitAvailability = businessUnitAvailability;
  }

  public Asset sharingProperties(SharingProperties sharingProperties) {
    this.sharingProperties = sharingProperties;
    return this;
  }

   /**
   * Get sharingProperties
   * @return sharingProperties
  **/
  @ApiModelProperty(value = "")
  public SharingProperties getSharingProperties() {
    return sharingProperties;
  }

  public void setSharingProperties(SharingProperties sharingProperties) {
    this.sharingProperties = sharingProperties;
  }

  public Asset template(Object template) {
    this.template = template;
    return this;
  }

   /**
   * Template the asset follows
   * @return template
  **/
  @ApiModelProperty(value = "Template the asset follows")
  public Object getTemplate() {
    return template;
  }

  public void setTemplate(Object template) {
    this.template = template;
  }

  public Asset file(String file) {
    this.file = file;
    return this;
  }

   /**
   * Base64-encoded string of a file associated with an asset
   * @return file
  **/
  @ApiModelProperty(value = "Base64-encoded string of a file associated with an asset")
  public String getFile() {
    return file;
  }

  public void setFile(String file) {
    this.file = file;
  }

  public Asset generateFrom(String generateFrom) {
    this.generateFrom = generateFrom;
    return this;
  }

   /**
   * Tells the sending compiler what view to use for generating this view&#39;s content
   * @return generateFrom
  **/
  @ApiModelProperty(value = "Tells the sending compiler what view to use for generating this view's content")
  public String getGenerateFrom() {
    return generateFrom;
  }

  public void setGenerateFrom(String generateFrom) {
    this.generateFrom = generateFrom;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Asset asset = (Asset) o;
    return Objects.equals(this.id, asset.id) &&
        Objects.equals(this.customerKey, asset.customerKey) &&
        Objects.equals(this.contentType, asset.contentType) &&
        Objects.equals(this.data, asset.data) &&
        Objects.equals(this.assetType, asset.assetType) &&
        Objects.equals(this.version, asset.version) &&
        Objects.equals(this.locked, asset.locked) &&
        Objects.equals(this.fileProperties, asset.fileProperties) &&
        Objects.equals(this.name, asset.name) &&
        Objects.equals(this.description, asset.description) &&
        Objects.equals(this.category, asset.category) &&
        Objects.equals(this.tags, asset.tags) &&
        Objects.equals(this.content, asset.content) &&
        Objects.equals(this.design, asset.design) &&
        Objects.equals(this.superContent, asset.superContent) &&
        Objects.equals(this.customFields, asset.customFields) &&
        Objects.equals(this.views, asset.views) &&
        Objects.equals(this.blocks, asset.blocks) &&
        Objects.equals(this.minBlocks, asset.minBlocks) &&
        Objects.equals(this.maxBlocks, asset.maxBlocks) &&
        Objects.equals(this.channels, asset.channels) &&
        Objects.equals(this.allowedBlocks, asset.allowedBlocks) &&
        Objects.equals(this.slots, asset.slots) &&
        Objects.equals(this.businessUnitAvailability, asset.businessUnitAvailability) &&
        Objects.equals(this.sharingProperties, asset.sharingProperties) &&
        Objects.equals(this.template, asset.template) &&
        Objects.equals(this.file, asset.file) &&
        Objects.equals(this.generateFrom, asset.generateFrom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, customerKey, contentType, data, assetType, version, locked, fileProperties, name, description, category, tags, content, design, superContent, customFields, views, blocks, minBlocks, maxBlocks, channels, allowedBlocks, slots, businessUnitAvailability, sharingProperties, template, file, generateFrom);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Asset {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    customerKey: ").append(toIndentedString(customerKey)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    assetType: ").append(toIndentedString(assetType)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    locked: ").append(toIndentedString(locked)).append("\n");
    sb.append("    fileProperties: ").append(toIndentedString(fileProperties)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    design: ").append(toIndentedString(design)).append("\n");
    sb.append("    superContent: ").append(toIndentedString(superContent)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    views: ").append(toIndentedString(views)).append("\n");
    sb.append("    blocks: ").append(toIndentedString(blocks)).append("\n");
    sb.append("    minBlocks: ").append(toIndentedString(minBlocks)).append("\n");
    sb.append("    maxBlocks: ").append(toIndentedString(maxBlocks)).append("\n");
    sb.append("    channels: ").append(toIndentedString(channels)).append("\n");
    sb.append("    allowedBlocks: ").append(toIndentedString(allowedBlocks)).append("\n");
    sb.append("    slots: ").append(toIndentedString(slots)).append("\n");
    sb.append("    businessUnitAvailability: ").append(toIndentedString(businessUnitAvailability)).append("\n");
    sb.append("    sharingProperties: ").append(toIndentedString(sharingProperties)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("    generateFrom: ").append(toIndentedString(generateFrom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

