/*
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.salesforce.marketingcloud.javasdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.salesforce.marketingcloud.javasdk.model.CreateSmsDefinitionContent;
import com.github.salesforce.marketingcloud.javasdk.model.CreateSmsDefinitionSubscriptions;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * CreateSmsDefinitionRequest
 */

public class CreateSmsDefinitionRequest {
  @SerializedName("definitionKey")
  private String definitionKey = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("content")
  private CreateSmsDefinitionContent content = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("createdDate")
  private OffsetDateTime createdDate = null;

  @SerializedName("modifiedDate")
  private OffsetDateTime modifiedDate = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("subscriptions")
  private CreateSmsDefinitionSubscriptions subscriptions = null;

  @SerializedName("requestId")
  private String requestId = null;

  public CreateSmsDefinitionRequest definitionKey(String definitionKey) {
    this.definitionKey = definitionKey;
    return this;
  }

   /**
   * Unique, user-generated key to access the definition object.
   * @return definitionKey
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "Unique, user-generated key to access the definition object.")
  public String getDefinitionKey() {
    return definitionKey;
  }

  public void setDefinitionKey(String definitionKey) {
    this.definitionKey = definitionKey;
  }

  public CreateSmsDefinitionRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the definition. Must be unique.
   * @return name
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "Name of the definition. Must be unique.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreateSmsDefinitionRequest content(CreateSmsDefinitionContent content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @NotNull
  @Valid
  @ApiModelProperty(required = true, value = "")
  public CreateSmsDefinitionContent getContent() {
    return content;
  }

  public void setContent(CreateSmsDefinitionContent content) {
    this.content = content;
  }

  public CreateSmsDefinitionRequest status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Operational state of the definition: active, inactive, or deleted. A message sent to an active definition is processed and delivered. A message sent to an inactive definition isn’t processed or delivered. Instead, the message is queued for later processing for up to three days.
   * @return status
  **/
  @ApiModelProperty(value = "Operational state of the definition: active, inactive, or deleted. A message sent to an active definition is processed and delivered. A message sent to an inactive definition isn’t processed or delivered. Instead, the message is queued for later processing for up to three days.")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

   /**
   * The date the object was created.
   * @return createdDate
  **/
  @Valid
  @ApiModelProperty(value = "The date the object was created.")
  public OffsetDateTime getCreatedDate() {
    return createdDate;
  }

   /**
   * The date the object was modified.
   * @return modifiedDate
  **/
  @Valid
  @ApiModelProperty(value = "The date the object was modified.")
  public OffsetDateTime getModifiedDate() {
    return modifiedDate;
  }

  public CreateSmsDefinitionRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * User-provided description of the SMS definition.
   * @return description
  **/
  @ApiModelProperty(value = "User-provided description of the SMS definition.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CreateSmsDefinitionRequest subscriptions(CreateSmsDefinitionSubscriptions subscriptions) {
    this.subscriptions = subscriptions;
    return this;
  }

   /**
   * Get subscriptions
   * @return subscriptions
  **/
  @NotNull
  @Valid
  @ApiModelProperty(required = true, value = "")
  public CreateSmsDefinitionSubscriptions getSubscriptions() {
    return subscriptions;
  }

  public void setSubscriptions(CreateSmsDefinitionSubscriptions subscriptions) {
    this.subscriptions = subscriptions;
  }

   /**
   * The ID of the request
   * @return requestId
  **/
  @ApiModelProperty(value = "The ID of the request")
  public String getRequestId() {
    return requestId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSmsDefinitionRequest createSmsDefinitionRequest = (CreateSmsDefinitionRequest) o;
    return Objects.equals(this.definitionKey, createSmsDefinitionRequest.definitionKey) &&
        Objects.equals(this.name, createSmsDefinitionRequest.name) &&
        Objects.equals(this.content, createSmsDefinitionRequest.content) &&
        Objects.equals(this.status, createSmsDefinitionRequest.status) &&
        Objects.equals(this.createdDate, createSmsDefinitionRequest.createdDate) &&
        Objects.equals(this.modifiedDate, createSmsDefinitionRequest.modifiedDate) &&
        Objects.equals(this.description, createSmsDefinitionRequest.description) &&
        Objects.equals(this.subscriptions, createSmsDefinitionRequest.subscriptions) &&
        Objects.equals(this.requestId, createSmsDefinitionRequest.requestId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(definitionKey, name, content, status, createdDate, modifiedDate, description, subscriptions, requestId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSmsDefinitionRequest {\n");
    
    sb.append("    definitionKey: ").append(toIndentedString(definitionKey)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    modifiedDate: ").append(toIndentedString(modifiedDate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    subscriptions: ").append(toIndentedString(subscriptions)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

