/*
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.salesforce.marketingcloud.javasdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.salesforce.marketingcloud.javasdk.model.EmailDefinition;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * EmailDefinitionsResponse
 */

public class EmailDefinitionsResponse {
  @SerializedName("requestId")
  private String requestId = null;

  @SerializedName("definitions")
  private List<EmailDefinition> definitions = null;

  @SerializedName("count")
  private BigDecimal count = null;

  @SerializedName("page")
  private BigDecimal page = null;

  @SerializedName("pageSize")
  private BigDecimal pageSize = null;

  public EmailDefinitionsResponse requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * The ID of the request
   * @return requestId
  **/
  @ApiModelProperty(value = "The ID of the request")
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  public EmailDefinitionsResponse definitions(List<EmailDefinition> definitions) {
    this.definitions = definitions;
    return this;
  }

  public EmailDefinitionsResponse addDefinitionsItem(EmailDefinition definitionsItem) {
    if (this.definitions == null) {
      this.definitions = new ArrayList<EmailDefinition>();
    }
    this.definitions.add(definitionsItem);
    return this;
  }

   /**
   * Get definitions
   * @return definitions
  **/
  @ApiModelProperty(value = "")
  public List<EmailDefinition> getDefinitions() {
    return definitions;
  }

  public void setDefinitions(List<EmailDefinition> definitions) {
    this.definitions = definitions;
  }

  public EmailDefinitionsResponse count(BigDecimal count) {
    this.count = count;
    return this;
  }

   /**
   * Number of pages
   * @return count
  **/
  @ApiModelProperty(value = "Number of pages")
  public BigDecimal getCount() {
    return count;
  }

  public void setCount(BigDecimal count) {
    this.count = count;
  }

  public EmailDefinitionsResponse page(BigDecimal page) {
    this.page = page;
    return this;
  }

   /**
   * Page number to return.
   * @return page
  **/
  @ApiModelProperty(value = "Page number to return.")
  public BigDecimal getPage() {
    return page;
  }

  public void setPage(BigDecimal page) {
    this.page = page;
  }

  public EmailDefinitionsResponse pageSize(BigDecimal pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Number of definitions, which are array elements, to return per paged response.
   * @return pageSize
  **/
  @ApiModelProperty(value = "Number of definitions, which are array elements, to return per paged response.")
  public BigDecimal getPageSize() {
    return pageSize;
  }

  public void setPageSize(BigDecimal pageSize) {
    this.pageSize = pageSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmailDefinitionsResponse emailDefinitionsResponse = (EmailDefinitionsResponse) o;
    return Objects.equals(this.requestId, emailDefinitionsResponse.requestId) &&
        Objects.equals(this.definitions, emailDefinitionsResponse.definitions) &&
        Objects.equals(this.count, emailDefinitionsResponse.count) &&
        Objects.equals(this.page, emailDefinitionsResponse.page) &&
        Objects.equals(this.pageSize, emailDefinitionsResponse.pageSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestId, definitions, count, page, pageSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmailDefinitionsResponse {\n");
    
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    definitions: ").append(toIndentedString(definitions)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

