/*
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.salesforce.marketingcloud.javasdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.salesforce.marketingcloud.javasdk.model.GetDefinitionsNotSentToRecipientsMessageInfo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.threeten.bp.OffsetDateTime;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * GetDefinitionsNotSentToRecipientsMessage
 */

public class GetDefinitionsNotSentToRecipientsMessage {
  @SerializedName("statusCode")
  private Integer statusCode = null;

  @SerializedName("statusMessage")
  private String statusMessage = null;

  @SerializedName("eventCategoryType")
  private String eventCategoryType = null;

  @SerializedName("timestamp")
  private OffsetDateTime timestamp = null;

  @SerializedName("definitionKey")
  private String definitionKey = null;

  @SerializedName("eventID")
  private BigDecimal eventID = null;

  @SerializedName("info")
  private GetDefinitionsNotSentToRecipientsMessageInfo info = null;

  public GetDefinitionsNotSentToRecipientsMessage statusCode(Integer statusCode) {
    this.statusCode = statusCode;
    return this;
  }

   /**
   * The specific status code
   * @return statusCode
  **/
  @ApiModelProperty(value = "The specific status code")
  public Integer getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(Integer statusCode) {
    this.statusCode = statusCode;
  }

  public GetDefinitionsNotSentToRecipientsMessage statusMessage(String statusMessage) {
    this.statusMessage = statusMessage;
    return this;
  }

   /**
   * The specific status message
   * @return statusMessage
  **/
  @ApiModelProperty(value = "The specific status message")
  public String getStatusMessage() {
    return statusMessage;
  }

  public void setStatusMessage(String statusMessage) {
    this.statusMessage = statusMessage;
  }

  public GetDefinitionsNotSentToRecipientsMessage eventCategoryType(String eventCategoryType) {
    this.eventCategoryType = eventCategoryType;
    return this;
  }

   /**
   * The status of the message
   * @return eventCategoryType
  **/
  @ApiModelProperty(value = "The status of the message")
  public String getEventCategoryType() {
    return eventCategoryType;
  }

  public void setEventCategoryType(String eventCategoryType) {
    this.eventCategoryType = eventCategoryType;
  }

  public GetDefinitionsNotSentToRecipientsMessage timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * The date the ...
   * @return timestamp
  **/
  @Valid
  @ApiModelProperty(value = "The date the ...")
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }

  public GetDefinitionsNotSentToRecipientsMessage definitionKey(String definitionKey) {
    this.definitionKey = definitionKey;
    return this;
  }

   /**
   * Unique, user-generated key to access the definition object.
   * @return definitionKey
  **/
  @ApiModelProperty(value = "Unique, user-generated key to access the definition object.")
  public String getDefinitionKey() {
    return definitionKey;
  }

  public void setDefinitionKey(String definitionKey) {
    this.definitionKey = definitionKey;
  }

  public GetDefinitionsNotSentToRecipientsMessage eventID(BigDecimal eventID) {
    this.eventID = eventID;
    return this;
  }

   /**
   * 
   * @return eventID
  **/
  @Valid
  @ApiModelProperty(value = "")
  public BigDecimal getEventID() {
    return eventID;
  }

  public void setEventID(BigDecimal eventID) {
    this.eventID = eventID;
  }

  public GetDefinitionsNotSentToRecipientsMessage info(GetDefinitionsNotSentToRecipientsMessageInfo info) {
    this.info = info;
    return this;
  }

   /**
   * Get info
   * @return info
  **/
  @Valid
  @ApiModelProperty(value = "")
  public GetDefinitionsNotSentToRecipientsMessageInfo getInfo() {
    return info;
  }

  public void setInfo(GetDefinitionsNotSentToRecipientsMessageInfo info) {
    this.info = info;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDefinitionsNotSentToRecipientsMessage getDefinitionsNotSentToRecipientsMessage = (GetDefinitionsNotSentToRecipientsMessage) o;
    return Objects.equals(this.statusCode, getDefinitionsNotSentToRecipientsMessage.statusCode) &&
        Objects.equals(this.statusMessage, getDefinitionsNotSentToRecipientsMessage.statusMessage) &&
        Objects.equals(this.eventCategoryType, getDefinitionsNotSentToRecipientsMessage.eventCategoryType) &&
        Objects.equals(this.timestamp, getDefinitionsNotSentToRecipientsMessage.timestamp) &&
        Objects.equals(this.definitionKey, getDefinitionsNotSentToRecipientsMessage.definitionKey) &&
        Objects.equals(this.eventID, getDefinitionsNotSentToRecipientsMessage.eventID) &&
        Objects.equals(this.info, getDefinitionsNotSentToRecipientsMessage.info);
  }

  @Override
  public int hashCode() {
    return Objects.hash(statusCode, statusMessage, eventCategoryType, timestamp, definitionKey, eventID, info);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDefinitionsNotSentToRecipientsMessage {\n");
    
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    statusMessage: ").append(toIndentedString(statusMessage)).append("\n");
    sb.append("    eventCategoryType: ").append(toIndentedString(eventCategoryType)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    definitionKey: ").append(toIndentedString(definitionKey)).append("\n");
    sb.append("    eventID: ").append(toIndentedString(eventID)).append("\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

