/*
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.salesforce.marketingcloud.javasdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.salesforce.marketingcloud.javasdk.model.GetDefinitionsNotSentToRecipientsMessage;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * GetDefinitionsNotSentToRecipientsResponse
 */

public class GetDefinitionsNotSentToRecipientsResponse {
  @SerializedName("lastEventID")
  private Integer lastEventID = null;

  @SerializedName("messages")
  private List<GetDefinitionsNotSentToRecipientsMessage> messages = null;

  @SerializedName("count")
  private Integer count = null;

  @SerializedName("requestId")
  private String requestId = null;

  @SerializedName("pageSize")
  private Integer pageSize = null;

  public GetDefinitionsNotSentToRecipientsResponse lastEventID(Integer lastEventID) {
    this.lastEventID = lastEventID;
    return this;
  }

   /**
   * Event ID from which you want the response to start. To obtain the initial event ID, submit a request without a lastEventId. The events in the response are listed top to bottom from oldest to newest
   * @return lastEventID
  **/
  @ApiModelProperty(value = "Event ID from which you want the response to start. To obtain the initial event ID, submit a request without a lastEventId. The events in the response are listed top to bottom from oldest to newest")
  public Integer getLastEventID() {
    return lastEventID;
  }

  public void setLastEventID(Integer lastEventID) {
    this.lastEventID = lastEventID;
  }

  public GetDefinitionsNotSentToRecipientsResponse messages(List<GetDefinitionsNotSentToRecipientsMessage> messages) {
    this.messages = messages;
    return this;
  }

  public GetDefinitionsNotSentToRecipientsResponse addMessagesItem(GetDefinitionsNotSentToRecipientsMessage messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<GetDefinitionsNotSentToRecipientsMessage>();
    }
    this.messages.add(messagesItem);
    return this;
  }

   /**
   * 
   * @return messages
  **/
  @ApiModelProperty(value = "")
  public List<GetDefinitionsNotSentToRecipientsMessage> getMessages() {
    return messages;
  }

  public void setMessages(List<GetDefinitionsNotSentToRecipientsMessage> messages) {
    this.messages = messages;
  }

  public GetDefinitionsNotSentToRecipientsResponse count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Number of pages
   * @return count
  **/
  @ApiModelProperty(value = "Number of pages")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

   /**
   * The ID of the request
   * @return requestId
  **/
  @ApiModelProperty(value = "The ID of the request")
  public String getRequestId() {
    return requestId;
  }

  public GetDefinitionsNotSentToRecipientsResponse pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Number of definitions, which are array elements, to return per paged response.
   * @return pageSize
  **/
  @ApiModelProperty(value = "Number of definitions, which are array elements, to return per paged response.")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDefinitionsNotSentToRecipientsResponse getDefinitionsNotSentToRecipientsResponse = (GetDefinitionsNotSentToRecipientsResponse) o;
    return Objects.equals(this.lastEventID, getDefinitionsNotSentToRecipientsResponse.lastEventID) &&
        Objects.equals(this.messages, getDefinitionsNotSentToRecipientsResponse.messages) &&
        Objects.equals(this.count, getDefinitionsNotSentToRecipientsResponse.count) &&
        Objects.equals(this.requestId, getDefinitionsNotSentToRecipientsResponse.requestId) &&
        Objects.equals(this.pageSize, getDefinitionsNotSentToRecipientsResponse.pageSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastEventID, messages, count, requestId, pageSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDefinitionsNotSentToRecipientsResponse {\n");
    
    sb.append("    lastEventID: ").append(toIndentedString(lastEventID)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

