/*
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.salesforce.marketingcloud.javasdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * GetDefinitionSendStatusForRecipientResponseInfo
 */

public class GetDefinitionSendStatusForRecipientResponseInfo {
  @SerializedName("messageKey")
  private String messageKey = null;

  @SerializedName("contactKey")
  private String contactKey = null;

  @SerializedName("to")
  private String to = null;

  @SerializedName("statusCode")
  private BigDecimal statusCode = null;

  @SerializedName("statusMessage")
  private String statusMessage = null;

  public GetDefinitionSendStatusForRecipientResponseInfo messageKey(String messageKey) {
    this.messageKey = messageKey;
    return this;
  }

   /**
   * Unique identifier used to track message status.
   * @return messageKey
  **/
  @ApiModelProperty(value = "Unique identifier used to track message status.")
  public String getMessageKey() {
    return messageKey;
  }

  public void setMessageKey(String messageKey) {
    this.messageKey = messageKey;
  }

  public GetDefinitionSendStatusForRecipientResponseInfo contactKey(String contactKey) {
    this.contactKey = contactKey;
    return this;
  }

   /**
   * Unique identifier for a subscriber in Marketing Cloud. Each request must include a contactKey. You can use an existing subscriber key or create one at send time by using the recipient’s email address.
   * @return contactKey
  **/
  @ApiModelProperty(value = "Unique identifier for a subscriber in Marketing Cloud. Each request must include a contactKey. You can use an existing subscriber key or create one at send time by using the recipient’s email address.")
  public String getContactKey() {
    return contactKey;
  }

  public void setContactKey(String contactKey) {
    this.contactKey = contactKey;
  }

  public GetDefinitionSendStatusForRecipientResponseInfo to(String to) {
    this.to = to;
    return this;
  }

   /**
   * Channel address of the recipient. For email, it’s the recipient&#39;s email address.
   * @return to
  **/
  @ApiModelProperty(value = "Channel address of the recipient. For email, it’s the recipient's email address.")
  public String getTo() {
    return to;
  }

  public void setTo(String to) {
    this.to = to;
  }

  public GetDefinitionSendStatusForRecipientResponseInfo statusCode(BigDecimal statusCode) {
    this.statusCode = statusCode;
    return this;
  }

   /**
   * The specific status code
   * @return statusCode
  **/
  @ApiModelProperty(value = "The specific status code")
  public BigDecimal getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(BigDecimal statusCode) {
    this.statusCode = statusCode;
  }

  public GetDefinitionSendStatusForRecipientResponseInfo statusMessage(String statusMessage) {
    this.statusMessage = statusMessage;
    return this;
  }

   /**
   * The specific status message
   * @return statusMessage
  **/
  @ApiModelProperty(value = "The specific status message")
  public String getStatusMessage() {
    return statusMessage;
  }

  public void setStatusMessage(String statusMessage) {
    this.statusMessage = statusMessage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDefinitionSendStatusForRecipientResponseInfo getDefinitionSendStatusForRecipientResponseInfo = (GetDefinitionSendStatusForRecipientResponseInfo) o;
    return Objects.equals(this.messageKey, getDefinitionSendStatusForRecipientResponseInfo.messageKey) &&
        Objects.equals(this.contactKey, getDefinitionSendStatusForRecipientResponseInfo.contactKey) &&
        Objects.equals(this.to, getDefinitionSendStatusForRecipientResponseInfo.to) &&
        Objects.equals(this.statusCode, getDefinitionSendStatusForRecipientResponseInfo.statusCode) &&
        Objects.equals(this.statusMessage, getDefinitionSendStatusForRecipientResponseInfo.statusMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageKey, contactKey, to, statusCode, statusMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDefinitionSendStatusForRecipientResponseInfo {\n");
    
    sb.append("    messageKey: ").append(toIndentedString(messageKey)).append("\n");
    sb.append("    contactKey: ").append(toIndentedString(contactKey)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    statusMessage: ").append(toIndentedString(statusMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

