/*
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.salesforce.marketingcloud.javasdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * GetQueueMetricsForSendDefinitionResponse
 */

public class GetQueueMetricsForSendDefinitionResponse {
  @SerializedName("requestId")
  private String requestId = null;

  @SerializedName("count")
  private BigDecimal count = null;

  @SerializedName("ageSeconds")
  private BigDecimal ageSeconds = null;

  public GetQueueMetricsForSendDefinitionResponse requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * The ID of the request
   * @return requestId
  **/
  @ApiModelProperty(value = "The ID of the request")
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  public GetQueueMetricsForSendDefinitionResponse count(BigDecimal count) {
    this.count = count;
    return this;
  }

   /**
   * Number of pages
   * @return count
  **/
  @ApiModelProperty(value = "Number of pages")
  public BigDecimal getCount() {
    return count;
  }

  public void setCount(BigDecimal count) {
    this.count = count;
  }

  public GetQueueMetricsForSendDefinitionResponse ageSeconds(BigDecimal ageSeconds) {
    this.ageSeconds = ageSeconds;
    return this;
  }

   /**
   * Number of seconds
   * @return ageSeconds
  **/
  @ApiModelProperty(value = "Number of seconds")
  public BigDecimal getAgeSeconds() {
    return ageSeconds;
  }

  public void setAgeSeconds(BigDecimal ageSeconds) {
    this.ageSeconds = ageSeconds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetQueueMetricsForSendDefinitionResponse getQueueMetricsForSendDefinitionResponse = (GetQueueMetricsForSendDefinitionResponse) o;
    return Objects.equals(this.requestId, getQueueMetricsForSendDefinitionResponse.requestId) &&
        Objects.equals(this.count, getQueueMetricsForSendDefinitionResponse.count) &&
        Objects.equals(this.ageSeconds, getQueueMetricsForSendDefinitionResponse.ageSeconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestId, count, ageSeconds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetQueueMetricsForSendDefinitionResponse {\n");
    
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    ageSeconds: ").append(toIndentedString(ageSeconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

