/*
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.salesforce.marketingcloud.javasdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.salesforce.marketingcloud.javasdk.model.CreateSmsDefinitionRequest;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * GetSmsDefinitionsResponse
 */

public class GetSmsDefinitionsResponse {
  @SerializedName("requestId")
  private String requestId = null;

  @SerializedName("definitions")
  private List<CreateSmsDefinitionRequest> definitions = null;

  @SerializedName("count")
  private Integer count = null;

  @SerializedName("page")
  private Integer page = null;

  @SerializedName("pageSize")
  private Integer pageSize = null;

  public GetSmsDefinitionsResponse requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * The ID of the request
   * @return requestId
  **/
  @ApiModelProperty(value = "The ID of the request")
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  public GetSmsDefinitionsResponse definitions(List<CreateSmsDefinitionRequest> definitions) {
    this.definitions = definitions;
    return this;
  }

  public GetSmsDefinitionsResponse addDefinitionsItem(CreateSmsDefinitionRequest definitionsItem) {
    if (this.definitions == null) {
      this.definitions = new ArrayList<CreateSmsDefinitionRequest>();
    }
    this.definitions.add(definitionsItem);
    return this;
  }

   /**
   * Get definitions
   * @return definitions
  **/
  @Valid
  @ApiModelProperty(value = "")
  public List<CreateSmsDefinitionRequest> getDefinitions() {
    return definitions;
  }

  public void setDefinitions(List<CreateSmsDefinitionRequest> definitions) {
    this.definitions = definitions;
  }

  public GetSmsDefinitionsResponse count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Number of pages
   * @return count
  **/
  @ApiModelProperty(value = "Number of pages")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public GetSmsDefinitionsResponse page(Integer page) {
    this.page = page;
    return this;
  }

   /**
   * Page number to return.
   * @return page
  **/
  @ApiModelProperty(value = "Page number to return.")
  public Integer getPage() {
    return page;
  }

  public void setPage(Integer page) {
    this.page = page;
  }

  public GetSmsDefinitionsResponse pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Number of definitions, which are array elements, to return per paged response.
   * @return pageSize
  **/
  @ApiModelProperty(value = "Number of definitions, which are array elements, to return per paged response.")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetSmsDefinitionsResponse getSmsDefinitionsResponse = (GetSmsDefinitionsResponse) o;
    return Objects.equals(this.requestId, getSmsDefinitionsResponse.requestId) &&
        Objects.equals(this.definitions, getSmsDefinitionsResponse.definitions) &&
        Objects.equals(this.count, getSmsDefinitionsResponse.count) &&
        Objects.equals(this.page, getSmsDefinitionsResponse.page) &&
        Objects.equals(this.pageSize, getSmsDefinitionsResponse.pageSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestId, definitions, count, page, pageSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetSmsDefinitionsResponse {\n");
    
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    definitions: ").append(toIndentedString(definitions)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

