/*
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.salesforce.marketingcloud.javasdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.salesforce.marketingcloud.javasdk.model.SendDefinitionResponseItem;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * SendDefinitionToSingleRecipientResponse
 */

public class SendDefinitionToSingleRecipientResponse {
  @SerializedName("requestId")
  private String requestId = null;

  @SerializedName("errorcode")
  private BigDecimal errorcode = null;

  @SerializedName("responses")
  private List<SendDefinitionResponseItem> responses = null;

  public SendDefinitionToSingleRecipientResponse requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * The ID of the request
   * @return requestId
  **/
  @ApiModelProperty(value = "The ID of the request")
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  public SendDefinitionToSingleRecipientResponse errorcode(BigDecimal errorcode) {
    this.errorcode = errorcode;
    return this;
  }

   /**
   * The specific error code
   * @return errorcode
  **/
  @Valid
  @ApiModelProperty(value = "The specific error code")
  public BigDecimal getErrorcode() {
    return errorcode;
  }

  public void setErrorcode(BigDecimal errorcode) {
    this.errorcode = errorcode;
  }

  public SendDefinitionToSingleRecipientResponse responses(List<SendDefinitionResponseItem> responses) {
    this.responses = responses;
    return this;
  }

  public SendDefinitionToSingleRecipientResponse addResponsesItem(SendDefinitionResponseItem responsesItem) {
    if (this.responses == null) {
      this.responses = new ArrayList<SendDefinitionResponseItem>();
    }
    this.responses.add(responsesItem);
    return this;
  }

   /**
   * 
   * @return responses
  **/
  @Valid
  @ApiModelProperty(value = "")
  public List<SendDefinitionResponseItem> getResponses() {
    return responses;
  }

  public void setResponses(List<SendDefinitionResponseItem> responses) {
    this.responses = responses;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendDefinitionToSingleRecipientResponse sendDefinitionToSingleRecipientResponse = (SendDefinitionToSingleRecipientResponse) o;
    return Objects.equals(this.requestId, sendDefinitionToSingleRecipientResponse.requestId) &&
        Objects.equals(this.errorcode, sendDefinitionToSingleRecipientResponse.errorcode) &&
        Objects.equals(this.responses, sendDefinitionToSingleRecipientResponse.responses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestId, errorcode, responses);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendDefinitionToSingleRecipientResponse {\n");
    
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    errorcode: ").append(toIndentedString(errorcode)).append("\n");
    sb.append("    responses: ").append(toIndentedString(responses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

