/*
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.salesforce.marketingcloud.javasdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.salesforce.marketingcloud.javasdk.model.CreateEmailDefinitionContent;
import com.github.salesforce.marketingcloud.javasdk.model.CreateEmailDefinitionOptionsRequest;
import com.github.salesforce.marketingcloud.javasdk.model.CreateEmailDefinitionSubscriptions;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * UpdateEmailDefinitionRequest
 */

public class UpdateEmailDefinitionRequest {
  @SerializedName("name")
  private String name = null;

  @SerializedName("content")
  private CreateEmailDefinitionContent content = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("classification")
  private String classification = null;

  @SerializedName("subscriptions")
  private CreateEmailDefinitionSubscriptions subscriptions = null;

  @SerializedName("options")
  private CreateEmailDefinitionOptionsRequest options = null;

  public UpdateEmailDefinitionRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the definition. Must be unique.
   * @return name
  **/
  @ApiModelProperty(value = "Name of the definition. Must be unique.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UpdateEmailDefinitionRequest content(CreateEmailDefinitionContent content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @ApiModelProperty(value = "")
  public CreateEmailDefinitionContent getContent() {
    return content;
  }

  public void setContent(CreateEmailDefinitionContent content) {
    this.content = content;
  }

  public UpdateEmailDefinitionRequest status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Operational state of the definition: active, inactive, or deleted. A message sent to an active definition is processed and delivered. A message sent to an inactive definition isn’t processed or delivered. Instead, the message is queued for later processing for up to three days.
   * @return status
  **/
  @ApiModelProperty(value = "Operational state of the definition: active, inactive, or deleted. A message sent to an active definition is processed and delivered. A message sent to an inactive definition isn’t processed or delivered. Instead, the message is queued for later processing for up to three days.")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public UpdateEmailDefinitionRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * User-provided description of the email definition.
   * @return description
  **/
  @ApiModelProperty(value = "User-provided description of the email definition.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public UpdateEmailDefinitionRequest classification(String classification) {
    this.classification = classification;
    return this;
  }

   /**
   * Marketing Cloud external key of a sending classification defined in Email Studio Administration. Only transactional classifications are permitted. Default is default transactional.
   * @return classification
  **/
  @ApiModelProperty(value = "Marketing Cloud external key of a sending classification defined in Email Studio Administration. Only transactional classifications are permitted. Default is default transactional.")
  public String getClassification() {
    return classification;
  }

  public void setClassification(String classification) {
    this.classification = classification;
  }

  public UpdateEmailDefinitionRequest subscriptions(CreateEmailDefinitionSubscriptions subscriptions) {
    this.subscriptions = subscriptions;
    return this;
  }

   /**
   * Get subscriptions
   * @return subscriptions
  **/
  @ApiModelProperty(value = "")
  public CreateEmailDefinitionSubscriptions getSubscriptions() {
    return subscriptions;
  }

  public void setSubscriptions(CreateEmailDefinitionSubscriptions subscriptions) {
    this.subscriptions = subscriptions;
  }

  public UpdateEmailDefinitionRequest options(CreateEmailDefinitionOptionsRequest options) {
    this.options = options;
    return this;
  }

   /**
   * Get options
   * @return options
  **/
  @ApiModelProperty(value = "")
  public CreateEmailDefinitionOptionsRequest getOptions() {
    return options;
  }

  public void setOptions(CreateEmailDefinitionOptionsRequest options) {
    this.options = options;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateEmailDefinitionRequest updateEmailDefinitionRequest = (UpdateEmailDefinitionRequest) o;
    return Objects.equals(this.name, updateEmailDefinitionRequest.name) &&
        Objects.equals(this.content, updateEmailDefinitionRequest.content) &&
        Objects.equals(this.status, updateEmailDefinitionRequest.status) &&
        Objects.equals(this.description, updateEmailDefinitionRequest.description) &&
        Objects.equals(this.classification, updateEmailDefinitionRequest.classification) &&
        Objects.equals(this.subscriptions, updateEmailDefinitionRequest.subscriptions) &&
        Objects.equals(this.options, updateEmailDefinitionRequest.options);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, content, status, description, classification, subscriptions, options);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateEmailDefinitionRequest {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    classification: ").append(toIndentedString(classification)).append("\n");
    sb.append("    subscriptions: ").append(toIndentedString(subscriptions)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

