/*
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.salesforce.marketingcloud.javasdk.api;

import com.github.salesforce.marketingcloud.javasdk.ApiException;
import com.github.salesforce.marketingcloud.javasdk.model.ApiError;
import com.github.salesforce.marketingcloud.javasdk.model.Asset;
import java.math.BigDecimal;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AssetApi
 */
@Ignore
public class AssetApiTest {

    private final AssetApi api = new AssetApi();

    
    /**
     * createAsset
     *
     * Creates a new asset.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAssetTest() throws ApiException {
        Asset body = null;
        Asset response = api.createAsset(body);

        // TODO: test validations
    }
    
    /**
     * deleteAsset
     *
     * Deletes an asset.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteAssetByIdTest() throws ApiException {
        BigDecimal id = null;
        api.deleteAssetById(id);

        // TODO: test validations
    }
    
    /**
     * getAssetById
     *
     * Gets an asset by ID.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAssetByIdTest() throws ApiException {
        BigDecimal id = null;
        Asset response = api.getAssetById(id);

        // TODO: test validations
    }
    
    /**
     * patchAsset
     *
     * Updates part of an asset.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void partiallyUpdateAssetTest() throws ApiException {
        BigDecimal id = null;
        Asset body = null;
        Asset response = api.partiallyUpdateAsset(id, body);

        // TODO: test validations
    }
    
}
