/*
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.salesforce.marketingcloud.javasdk.api;

import com.github.salesforce.marketingcloud.javasdk.ApiException;
import com.github.salesforce.marketingcloud.javasdk.model.ApiError;

import java.lang.reflect.InvocationTargetException;
import java.math.BigDecimal;
import com.github.salesforce.marketingcloud.javasdk.model.Campaign;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CampaignApi
 */
@Ignore
public class CampaignApiTest //extends ApiTest
{
    private final CampaignApi api;

    public CampaignApiTest() throws ClassNotFoundException, NoSuchMethodException, InvocationTargetException, InstantiationException, IllegalAccessException {
        this.api = new ApiSutFactory<>(CampaignApi.class).create();
    }

    /**
     * createCampaign
     *
     * Creates a campaign.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createCampaignTest() throws ApiException {
        Campaign body = null;
        Campaign response = api.createCampaign(body);

        // TODO: test validations
    }
    
    /**
     * deleteCampaign
     *
     * Deletes a campaign.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCampaignByIdTest() throws ApiException {
        String id = null;
        api.deleteCampaignById(id);

        // TODO: test validations
    }
    
    /**
     * getCampaign
     *
     * Retrieves a campaign.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCampaignByIdTest() throws ApiException {
        String id = null;
        Campaign response = api.getCampaignById(id);

        // TODO: test validations
    }
    
}
