/*
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.salesforce.marketingcloud.javasdk.api;

import com.github.salesforce.marketingcloud.javasdk.ApiException;
import com.github.salesforce.marketingcloud.javasdk.model.ApiError;
import java.math.BigDecimal;
import com.github.salesforce.marketingcloud.javasdk.model.EmailDefinition;
import com.github.salesforce.marketingcloud.javasdk.model.EmailDefinitionDescription;
import com.github.salesforce.marketingcloud.javasdk.model.EmailDefinitionsResponse;
import com.github.salesforce.marketingcloud.javasdk.model.SuccessfulEmailDefinitionDelete;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmailDefinitionApi
 */
@Ignore
public class EmailDefinitionApiTest extends ApiTest {

    private final EmailDefinitionApi api = new EmailDefinitionApi(
            authBasePath,
            clientId,
            clientSecret,
            accountId,
            scope);
    
    /**
     * createEmailDefinition
     *
     * Creates the definition for an email.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createEmailDefinitionTest() throws ApiException {
        EmailDefinition body = null;
        EmailDefinition response = api.createEmailDefinition(body);

        // TODO: test validations
    }
    
    /**
     * deleteEmailDefinition
     *
     * Deletes the definition for an email.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteEmailDefinitionByDefinitionKeyTest() throws ApiException {
        String definitionKey = null;
        SuccessfulEmailDefinitionDelete response = api.deleteEmailDefinitionByDefinitionKey(definitionKey);

        // TODO: test validations
    }
    
    /**
     * getEmailDefinition
     *
     * Gets send definition configuration details for a definition key.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEmailDefinitionByDefinitionKeyTest() throws ApiException {
        String definitionKey = null;
        EmailDefinition response = api.getEmailDefinitionByDefinitionKey(definitionKey);

        // TODO: test validations
    }
    
    /**
     * getEmailDefinitions
     *
     * Gets a list of send definitions.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEmailDefinitionsTest() throws ApiException {
        String filter = null;
        BigDecimal pageSize = null;
        BigDecimal page = null;
        String orderBy = null;
        EmailDefinitionsResponse response = api.getEmailDefinitions(filter, pageSize, page, orderBy);

        // TODO: test validations
    }
    
    /**
     * patchEmailDefinition
     *
     * Updates a specific email definition.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void partiallyUpdateEmailDefinitionTest() throws ApiException {
        String definitionKey = null;
        EmailDefinitionDescription body = null;
        EmailDefinition response = api.partiallyUpdateEmailDefinition(definitionKey, body);

        // TODO: test validations
    }
    
}
